services:
  - type: web
    name: adcp-demo
    env: python
    plan: starter
    buildCommand: make install
    startCommand: make start
    envVars:
      - key: DB_URL
        value: sqlite:///./data/adcp_demo.sqlite3
      - key: SERVICE_BASE_URL
        value: https://the-agentic-future-is-here-5.onrender.com
      - key: DEBUG
        value: 0
      - key: EMBEDDINGS_PROVIDER
        value: gemini
      - key: EMBEDDINGS_MODEL
        value: text-embedding-004
      - key: EMB_CONCURRENCY
        value: "2"
      - key: EMB_BATCH_SIZE
        value: "32"
      - key: GEMINI_API_KEY
        sync: false
      - key: SKIP_REFERENCE_VALIDATION
        value: "true"
    disk:
      name: data
      mountPath: ./data
      sizeGB: 1

